// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCBc15pF32vQ_DRxx0aP-m26BtDLIAlBA',
    appId: '1:879521057242:android:01d708b4875e52ef3e58e3',
    messagingSenderId: '879521057242',
    projectId: 'workoutapp-616d04',
    storageBucket: 'workoutapp-616d04.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrKxfHUrSwd4ayb0N6EIUsaz7AOhcGAhQ',
    appId: '1:879521057242:ios:d583944b594027493e58e3',
    messagingSenderId: '879521057242',
    projectId: 'workoutapp-616d04',
    storageBucket: 'workoutapp-616d04.appspot.com',
    androidClientId: '879521057242-7hoscgka63ogrfatj2rmet59a57fdtp3.apps.googleusercontent.com',
    iosClientId: '879521057242-e81ulnapjo1du206lkq282lj58g8vidj.apps.googleusercontent.com',
    iosBundleId: 'com.example.liftura2',
  );

}